trigger:
- master   # runs when code is pushed to main branch

pool:
 vmImage: 'ubuntu-latest'
steps:
- script: mvn validate
  displayName: 'Maven Validate'

- script: mvn compile
  displayName: 'Maven Compile'